# Dependencies
markdown:	kramdown
highlighter:	'pygments'

# Permalinks
#permalink:	/blog/:title

# Setup
title:		fabio vitalba
tagline:	'blog'
description:	'My coding blog.'
url:		http://fishinggiraffe.com

author:
  name:		'Fabio Vitalba'
  url:		https://github.com/fabiovitalba
  email:  fabio.vitalba@fishinggiraffe.com

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/fabiovitalba
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/fabiovitalba
    desc:	Fork me on github

twitter_username: fabiovitalba
github_username:  fabiovitalba

menu:
  - title:	Home
    url:	/

  - title:	About
    url:	/about

copyright:
  author:	Fabio Vitalba
  url:		http://fishinggiraffe.com
#  type_title:	Some rights reserved
#  type_url:	http://creativecommons.org/licenses/by-nc/2.5
